package smol_access.themes

data class Theme(
    val isDark: Boolean = true,
    val primary: String? = null,
    val primaryVariant: String? = null,
    val secondary: String? = null,
    val secondaryVariant: String? = null,
    val background: String? = null,
    val surface: String? = null,
    val error: String? = null,
    val onPrimary: String? = null,
    val onSecondary: String? = null,
    val onBackground: String? = null,
    val onSurface: String? = null,
    val onError: String? = null,
) {
    constructor(
        isDark: Boolean,
        primary: Long? = null,
        primaryVariant: Long? = null,
        secondary: Long? = null,
        secondaryVariant: Long? = null,
        background: Long? = null,
        surface: Long? = null,
        error: Long? = null,
        onPrimary: Long? = null,
        onSecondary: Long? = null,
        onBackground: Long? = null,
        onSurface: Long? = null,
        onError: Long? = null,
    ) : this(
        isDark = isDark,
        primary = primary?.toString(radix = 16),
        primaryVariant = primaryVariant?.toString(radix = 16),
        secondary = secondary?.toString(radix = 16),
        secondaryVariant = secondaryVariant?.toString(radix = 16),
        background = background?.toString(radix = 16),
        surface = surface?.toString(radix = 16),
        error = error?.toString(radix = 16),
        onPrimary = onPrimary?.toString(radix = 16),
        onSecondary = onSecondary?.toString(radix = 16),
        onBackground = onBackground?.toString(radix = 16),
        onSurface = onSurface?.toString(radix = 16),
        onError = onError?.toString(radix = 16),
    )
}